---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 13.5.3

verifier:
  name: inspec

platforms:
  - name: windows10pro
    driver:
      box: hieunb/windows10pro
      communicator: winrm
    transport:
      name: winrm
      username: vagrant
      password: vagrant

suites:
  - name: install
    run_list:
      - recipe[test::install]
    verifier:
      inspec_tests:
        - test/integration/install
    attributes:
